function Import_STARSInpatient_FGAOutcomes = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  STARSINPATIENTINFOOUTCOMESS5 = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  STARSINPATIENTINFOOUTCOMESS5 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  STARSINPATIENTINFOOUTCOMESS5 = IMPORTFILE(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  STARSInpatientInfoOutcomesS5 = importfile("Y:\STARS\Inpatient Study\STARS_Inpatient_Info_Outcomes.xlsx", "FGA", [2, 34]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jul-2022 13:51:22

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 34];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 14);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "D" + dataLines(1, 1) + ":Q" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["FGAScore", "Items", "FGA01", "FGA02", "FGA03", "FGA04", "FGA05", "FGA06", "FGA07", "FGA08", "FGA09", "FGA10", "FGA10_a", "FGA10_b"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
Import_STARSInpatient_FGAOutcomes = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "D" + dataLines(idx, 1) + ":Q" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Import_STARSInpatient_FGAOutcomes = [Import_STARSInpatient_FGAOutcomes; tb]; %#ok<AGROW>
end

end