function Import_STARSInpatient_VGAOutcomes = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  STARSINPATIENTINFOOUTCOMESS2 = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  STARSINPATIENTINFOOUTCOMESS2 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  STARSINPATIENTINFOOUTCOMESS2 = IMPORTFILE(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  STARSInpatientInfoOutcomesS2 = importfile("Y:\STARS\Inpatient Study\STARS_Inpatient_Info_Outcomes.xlsx", "VGA", [2, 34]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jul-2022 13:42:41

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 34];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "D" + dataLines(1, 1) + ":H" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Item1", "Item2", "Item3", "Item4", "Item5"];
opts.VariableTypes = ["double", "double", "double", "double", "double"];

% Import the data
Import_STARSInpatient_VGAOutcomes = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "D" + dataLines(idx, 1) + ":H" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Import_STARSInpatient_VGAOutcomes = [Import_STARSInpatient_VGAOutcomes; tb]; %#ok<AGROW>
end

end