function Import_STARSInpatient_10MWTOutcomes = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  STARSINPATIENTINFOOUTCOMESS1 = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  STARSINPATIENTINFOOUTCOMESS1 = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  STARSINPATIENTINFOOUTCOMESS1 = IMPORTFILE(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  STARSInpatientInfoOutcomesS1 = importfile("Y:\STARS\Inpatient Study\STARS_Inpatient_Info_Outcomes.xlsx", "10MWT", [2, 15]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jul-2022 13:37:43

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 16];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 12);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "D" + dataLines(1, 1) + ":O" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Distance", "SSVTrial1", "SSVTrial2", "SSVTrial3", "SSVTrial4", "MWT_SSV", "FVTrial1", "FVTrial2", "FVTrial3", "MWT_FV", "AssistiveDevice", "LevelAssist"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "string"];

% Specify variable properties
opts = setvaropts(opts, "LevelAssist", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["AssistiveDevice", "LevelAssist"], "EmptyFieldRule", "auto");

% Import the data
Import_STARSInpatient_10MWTOutcomes = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "D" + dataLines(idx, 1) + ":N" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    Import_STARSInpatient_10MWTOutcomes = [Import_STARSInpatient_10MWTOutcomes; tb]; %#ok<AGROW>
end

end