function STARSInpatientIdentifiers = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  STARSINPATIENTINFOOUTCOMES = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  STARSINPATIENTINFOOUTCOMES = IMPORTFILE(FILE, SHEET) reads from the
%  specified worksheet.
%
%  STARSINPATIENTINFOOUTCOMES = IMPORTFILE(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  STARSInpatientInfoOutcomes = importfile("Y:\STARS\Inpatient Study\STARS_Inpatient_Info_Outcomes.xlsx", "SubjInfo", [2, 15]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jul-2022 13:24:21

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 15];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 3);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":C" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["ID", "SessionID", "TestDay"];
opts.VariableTypes = ["categorical", "categorical", "datetime"];

% Specify variable properties
opts = setvaropts(opts, ["ID", "SessionID"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "TestDay", "InputFormat", "");

% Import the data
STARSInpatientIdentifiers = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":C" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    STARSInpatientIdentifiers = [STARSInpatientIdentifiers; tb]; %#ok<AGROW>
end

end